import type { WorkspaceImageMode, WorkspaceVideoMode } from "@/lib/workspace-registry";

export type TemplateCategory =
  | "商品美食"
  | "海报品牌"
  | "摄影人像"
  | "插画风格"
  | "图文科普"
  | "界面设计"
  | "图片编辑";

type TemplateBase = {
  id: string;
  label: string;
  summary: string;
  thumbnail: string;
  category: TemplateCategory;
  prompt: string;
  requiresImage: boolean;
  featured: boolean;
};

export type ImagePromptTemplate = TemplateBase & {
  scope: "image";
  targetToolId: "image" | "image-editor";
  mode: WorkspaceImageMode;
  aspectRatio: string;
  quality: "1k" | "2k";
};

export type VideoPromptTemplate = TemplateBase & {
  scope: "video";
  targetToolId: "video";
  mode: WorkspaceVideoMode;
  aspectRatio: string;
  duration: number;
};

export type TemplatePromptTemplate = ImagePromptTemplate | VideoPromptTemplate;

export const templateCategories: Array<TemplateCategory | "全部"> = [
  "全部",
  "商品美食",
  "海报品牌",
  "摄影人像",
  "插画风格",
  "图文科普",
  "界面设计",
  "图片编辑",
];

export const imagePromptTemplates: ImagePromptTemplate[] = [
  {
    id: "product-hero",
    scope: "image",
    label: "商品主图",
    summary: "主体居中，背景干净，适合电商首图。",
    thumbnail: "/images/reference/hero-cover.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: false,
    featured: true,
    prompt: "生成一张 TikTok Shop 商品主图，商品主体居中，占画面主要位置，背景干净，光线柔和，突出材质、颜色和核心卖点。",
  },
  {
    id: "white-background",
    scope: "image",
    label: "纯白背景",
    summary: "纯白背景，突出商品轮廓和质感。",
    thumbnail: "/images/reference/sample-2.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: false,
    featured: true,
    prompt: "生成一张纯白背景商品图，主体边缘清晰，阴影自然，画面干净，适合 TikTok Shop 商品展示。",
  },
  {
    id: "product-scene",
    scope: "image",
    label: "商品场景图",
    summary: "把商品放进真实使用场景。",
    thumbnail: "/auth-showcase/product-scene.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: false,
    featured: true,
    prompt: "生成一张商品场景图，把商品放在真实使用环境中，场景自然、有生活感，突出商品用途和 TikTok Shop 转化卖点。",
  },
  {
    id: "premium-perfume",
    scope: "image",
    label: "新中式香水",
    summary: "东方空间、花材和产品质感结合。",
    thumbnail: "/tutorials/image-generator/perfume-result.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: true,
    prompt: "新中式香水产品摄影，粉色牡丹花簇拥，香水瓶置于大理石台面，背景带有中式窗棂元素，光影柔和，画面干净高级，细节丰富，商业产品图风格。",
  },
  {
    id: "food-editorial",
    scope: "image",
    label: "美食海报",
    summary: "适合餐饮新品、甜品和饮品展示。",
    thumbnail: "/images/reference/sample-1.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "3:4",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "竖版 3:4 美食商业摄影，一份精致甜品放在陶瓷餐盘中，周围有新鲜水果、奶油和细小糖粉，暖色侧光，浅景深，背景干净，画面有菜单封面和社交媒体海报质感。",
  },
  {
    id: "fashion-editorial",
    scope: "image",
    label: "服装大片",
    summary: "服饰、配饰和生活方式视觉。",
    thumbnail: "/images/reference/sample-3.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "2:3",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "竖版时尚编辑大片，一位模特穿着简洁高级的春夏服装，站在自然光室内空间，衣料纹理清楚，姿态自然，背景克制，整体像品牌 lookbook 封面，不出现真实品牌标识。",
  },
  {
    id: "promo-poster",
    scope: "image",
    label: "促销海报",
    summary: "预留促销信息位，突出活动氛围。",
    thumbnail: "/images/reference/sample-2.png",
    category: "海报品牌",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "4:5",
    quality: "2k",
    requiresImage: false,
    featured: true,
    prompt: "设计一张 3:4 竖版促销海报，商品醒目，画面有活动氛围，预留清晰的标题、价格和行动按钮区域，层级明确，商业感强，适合社交媒体投放。",
  },
  {
    id: "typography-poster",
    scope: "image",
    label: "字体海报",
    summary: "强调标题文字和版式节奏。",
    thumbnail: "/images/reference/sample-1.png",
    category: "海报品牌",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "3:4",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "设计一张 3:4 竖版字体海报，准确显示中文标题“夏日灵感周”和副标题“新鲜、明亮、轻盈”，大标题清楚可读，使用现代中文排版、网格系统、留白和少量粉紫强调色，不要出现乱码。",
  },
  {
    id: "brand-identity-board",
    scope: "image",
    label: "品牌视觉板",
    summary: "展示 Logo、色彩、包装和应用场景。",
    thumbnail: "/auth-showcase/video-cover.png",
    category: "海报品牌",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 16:9 品牌视觉板，为一个虚构生活方式品牌“AURORA STUDIO”设计展示页，包含标志、主色板、字体样张、包装小样、社交媒体封面和名片应用，布局整洁，文字清晰，现代高级。",
  },
  {
    id: "event-poster",
    scope: "image",
    label: "活动主视觉",
    summary: "适合发布会、市集、展览活动。",
    thumbnail: "/images/reference/hero-cover.png",
    category: "海报品牌",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 16:9 活动主视觉海报，主题是“城市创意生活节”，画面包含舞台、展位、灯光、人群剪影和品牌视觉元素，标题区清晰，留出日期和地点信息位置，风格年轻但不杂乱。",
  },
  {
    id: "portrait-studio",
    scope: "image",
    label: "棚拍人像",
    summary: "干净人像、头像和个人品牌照。",
    thumbnail: "/tutorials/video-generator/input-person.png",
    category: "摄影人像",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "2:3",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "竖版 2:3 专业棚拍人像，一位年轻创作者面对镜头，自然微笑，柔和主光和轮廓光，背景为深灰渐变，皮肤质感真实，服装简洁，适合个人主页头像和品牌介绍。",
  },
  {
    id: "street-photography",
    scope: "image",
    label: "街头摄影",
    summary: "真实城市氛围和自然光影。",
    thumbnail: "/tutorials/video-generator/rain-umbrella.png",
    category: "摄影人像",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 16:9 写实街头摄影，雨天中国城市街头，透明雨伞、湿润柏油路、霓虹招牌反光、行人和共享单车，画面像真实相机抓拍，光线自然，细节丰富，不过度电影化。",
  },
  {
    id: "interior-photography",
    scope: "image",
    label: "室内空间",
    summary: "家居、展厅和商业空间氛围图。",
    thumbnail: "/tutorials/image-editor/merge-scene.png",
    category: "摄影人像",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 16:9 室内空间摄影，现代东方茶室，木质桌椅、低矮花器、亚麻窗帘、柔和天光和墙面投影，空间干净有层次，适合作为家居品牌或空间设计展示图。",
  },
  {
    id: "travel-photo",
    scope: "image",
    label: "旅行纪实",
    summary: "自然景观、城市旅行和生活方式。",
    thumbnail: "/images/reference/sample-3.png",
    category: "摄影人像",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "3:2",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 3:2 旅行纪实照片，清晨古城街巷，石板路、木窗、早餐摊、远处行人和柔和阳光，色彩真实，像相机原片，有生活气息，不要过度滤镜。",
  },
  {
    id: "anime-character",
    scope: "image",
    label: "动漫角色",
    summary: "角色立绘、社交头像和设定稿。",
    thumbnail: "/images/reference/sample-1.png",
    category: "插画风格",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "2:3",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "竖版 2:3 动漫角色立绘，一位原创未来城市少女，短外套、耳机、发光配饰和轻便背包，站姿清楚，表情自信，背景简洁，线稿干净，配色统一，不模仿真实 IP。",
  },
  {
    id: "watercolor-illustration",
    scope: "image",
    label: "水彩插画",
    summary: "柔和手绘、书籍和包装插图。",
    thumbnail: "/images/reference/sample-2.png",
    category: "插画风格",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "4:3",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 4:3 水彩插画，一间安静花店，木质门头、玻璃窗、鲜花桶、猫和雨后街道，颜色柔和，纸张纹理可见，边缘自然晕染，适合绘本或生活方式品牌插图。",
  },
  {
    id: "chinese-ink",
    scope: "image",
    label: "国风水墨",
    summary: "东方审美、山水和留白构图。",
    thumbnail: "/tutorials/image-generator/idea-main.svg",
    category: "插画风格",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 16:9 现代国风水墨插画，远山、薄雾、松枝、小桥和一盏温暖灯光，墨色层次清楚，留白充足，少量淡粉色点缀，适合高端文化产品背景。",
  },
  {
    id: "pixel-game-scene",
    scope: "image",
    label: "像素场景",
    summary: "游戏封面、关卡氛围和复古视觉。",
    thumbnail: "/images/reference/hero-cover.png",
    category: "插画风格",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 16:9 像素艺术游戏场景，夜晚小镇、雨水、便利店灯光、远处霓虹和主角背影，像素边缘清晰，色彩统一，有复古游戏封面感。",
  },
  {
    id: "tattoo-flash",
    scope: "image",
    label: "纹身图案",
    summary: "适合纹身闪图、图案设计和灵感板。",
    thumbnail: "/images/reference/sample-3.png",
    category: "插画风格",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "2:3",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "竖版 2:3 纹身设计闪图，一只月亮飞蛾、黑玫瑰、细线星轨和轻微哥特装饰，黑灰线稿为主，少量冷紫色点缀，线条清晰，留白充足，像专业纹身图案展示纸，不出现真实皮肤。",
  },
  {
    id: "infographic-board",
    scope: "image",
    label: "信息图卡",
    summary: "拆解说明、知识卡片和流程图。",
    thumbnail: "/tutorials/image-generator/result-main.svg",
    category: "图文科普",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 16:9 中文信息图，主题“冷萃咖啡风味指南”，固定布局包含顶部标题、左侧风味轮、右侧制作流程、底部参数表，使用清晰中文标签、细线引导、柔和配色和充足留白，不要乱码。",
  },
  {
    id: "research-diagram",
    scope: "image",
    label: "论文示意图",
    summary: "研究流程、模型结构和论文插图。",
    thumbnail: "/tutorials/image-generator/result-left.svg",
    category: "图文科普",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 16:9 论文风格流程示意图，主题“多模态内容生成工作流”，从左到右包含输入、理解、规划、生成、质检五个模块，使用箭头、编号、图例和简洁标签，白底，学术会议图表质感。",
  },
  {
    id: "data-dashboard-card",
    scope: "image",
    label: "数据图表",
    summary: "报告、看板和趋势可视化。",
    thumbnail: "/auth-showcase/product-main.png",
    category: "图文科普",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 16:9 数据可视化报告页，主题“内容投放效果概览”，包含折线图、柱状图、渠道占比、关键指标卡和简短中文注释，网格对齐，标签清晰，商务报告风格。",
  },
  {
    id: "field-guide",
    scope: "image",
    label: "科普图鉴",
    summary: "自然、器物和知识图鉴。",
    thumbnail: "/images/reference/sample-2.png",
    category: "图文科普",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "3:4",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "竖版 3:4 中文科普图鉴，主题“常见香料植物”，包含 6 个植物小图、名称标签、简短风味说明和底部说明栏，像博物馆展板，排版清楚，文字可读，不要乱码。",
  },
  {
    id: "wayfinding-map",
    scope: "image",
    label: "导览地图",
    summary: "景区、展馆和活动现场导览图。",
    thumbnail: "/tutorials/image-generator/result-right.svg",
    category: "图文科普",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "3:2",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 3:2 中文导览地图，主题“城市创意市集导览图”，包含入口、主舞台、餐饮区、手作区、休息区、卫生间、服务台和出口，路线清楚，图例完整，插画风格友好，标签清晰可读。",
  },
  {
    id: "mobile-app-mockup",
    scope: "image",
    label: "手机界面",
    summary: "移动 App 首屏和产品概念稿。",
    thumbnail: "/auth-showcase/video-cover.png",
    category: "界面设计",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "9:16",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "9:16 手机界面设计稿，为虚构习惯管理 App“Dayline”设计首页，包含顶部问候语、今日进度环、习惯列表、数据小卡片和底部导航，深色背景，粉紫强调色，图标对齐，文字清晰。",
  },
  {
    id: "saas-dashboard",
    scope: "image",
    label: "工作台界面",
    summary: "SaaS 后台、数据面板和工具页。",
    thumbnail: "/auth-showcase/product-main.png",
    category: "界面设计",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "16:9 桌面端 SaaS 工作台界面，为虚构 AI 内容平台设计深色仪表盘，包含左侧导航、顶部指标、任务列表、预览区和状态卡片，布局紧凑专业，组件边框细腻，文字清楚。",
  },
  {
    id: "landing-hero",
    scope: "image",
    label: "落地页首屏",
    summary: "产品官网、活动页和品牌首屏。",
    thumbnail: "/tutorials/image-generator/idea-right.svg",
    category: "界面设计",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "16:9 产品落地页首屏视觉，为虚构创意工具“Aurora Canvas”设计网页首屏，左侧标题、短副标题和主要按钮，右侧为真实产品界面预览，深色高级风格，粉紫少量强调，排版清晰。",
  },
  {
    id: "app-icon-set",
    scope: "image",
    label: "图标套组",
    summary: "功能图标、应用图标和视觉系统。",
    thumbnail: "/tutorials/image-generator/ratio-square.svg",
    category: "界面设计",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "正方形 1:1 图标套组，设计 12 个统一风格的 AI 创作工具图标，包含视频、图片、编辑、高清、模板、作品库等主题，线性加微渐变风格，圆角统一，深色背景上清晰可见。",
  },
  {
    id: "multi-angle",
    scope: "image",
    label: "多角度展示",
    summary: "用多角度展现商品外观。",
    thumbnail: "/images/reference/sample-1.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成商品多角度展示图，围绕主体展示正面、侧面和细节视角，画面统一，适合 TikTok Shop 商品讲解。",
  },
  {
    id: "detail-shot",
    scope: "image",
    label: "商品细节图",
    summary: "放大材质、纹理和关键细节。",
    thumbnail: "/images/reference/sample-3.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成商品细节展示图，突出材质、纹理、结构和功能亮点，画面干净，适合电商详情页。",
  },
  {
    id: "text-translation",
    scope: "image",
    label: "文字翻译",
    summary: "翻译画面文字，并保持原布局。",
    thumbnail: "/images/reference/sample-3.png",
    category: "图片编辑",
    targetToolId: "image-editor",
    mode: "image-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: true,
    featured: true,
    prompt: "基于上传图像翻译画面中的文字，保持原始排版、布局、字体风格和商品主体不变，翻译后画面自然清晰。",
  },
  {
    id: "smart-cutout",
    scope: "image",
    label: "智能抠图",
    summary: "自动抠出主体，保留边缘细节。",
    thumbnail: "/images/reference/sample-1.png",
    category: "图片编辑",
    targetToolId: "image-editor",
    mode: "image-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: true,
    featured: false,
    prompt: "基于上传图像智能抠出主体，保持原始比例和主体细节，输出透明背景，边缘干净自然。",
  },
  {
    id: "background-replace",
    scope: "image",
    label: "替换背景",
    summary: "保留主体，换成更适合的场景。",
    thumbnail: "/tutorials/image-editor/merge-result.png",
    category: "图片编辑",
    targetToolId: "image-editor",
    mode: "image-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: true,
    featured: false,
    prompt: "基于上传图像保留主体、姿态和光影方向不变，将背景替换为干净高级的室内商业场景，主体边缘自然融合，材质和阴影保持真实。",
  },
  {
    id: "object-remove",
    scope: "image",
    label: "去除杂物",
    summary: "清理多余物体和画面干扰。",
    thumbnail: "/tutorials/image-editor/single-result.png",
    category: "图片编辑",
    targetToolId: "image-editor",
    mode: "image-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: true,
    featured: false,
    prompt: "基于上传图像去除画面中多余杂物、污渍、反光和背景干扰，保持主体、构图和真实光影不变，修复区域自然不可见。",
  },
  {
    id: "style-transfer",
    scope: "image",
    label: "风格统一",
    summary: "把素材统一成同一视觉风格。",
    thumbnail: "/tutorials/image-editor/detail-one.svg",
    category: "图片编辑",
    targetToolId: "image-editor",
    mode: "image-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: true,
    featured: false,
    prompt: "基于上传图像保持主体结构和关键细节不变，将整体视觉统一为高级商业摄影风格，调整色彩、光影和背景质感，使画面更干净专业。",
  },
];

export const videoPromptTemplates: VideoPromptTemplate[] = [
  {
    id: "product-rotation",
    scope: "video",
    label: "商品旋转",
    summary: "商品缓慢旋转，突出外观和质感。",
    thumbnail: "/images/reference/hero-cover.png",
    category: "商品美食",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 5,
    requiresImage: false,
    featured: true,
    prompt: "生成 TikTok Shop 商品旋转展示短视频，商品居中缓慢旋转，镜头稳定，光线干净，突出外观、材质和卖点。",
  },
  {
    id: "detail-closeup",
    scope: "video",
    label: "细节特写",
    summary: "镜头推进，展示商品细节。",
    thumbnail: "/images/reference/sample-3.png",
    category: "商品美食",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 5,
    requiresImage: false,
    featured: true,
    prompt: "生成商品细节特写短视频，镜头缓慢推进，展示材质、纹理、按键、接口或功能细节，节奏清楚，适合 TikTok 商品展示。",
  },
  {
    id: "usage-demo",
    scope: "video",
    label: "使用展示",
    summary: "展示真实使用动作和效果。",
    thumbnail: "/images/reference/sample-1.png",
    category: "商品美食",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 8,
    requiresImage: false,
    featured: true,
    prompt: "生成穿戴或使用展示短视频，展示用户如何自然使用商品，动作连贯，场景真实，突出使用效果和日常适用性。",
  },
  {
    id: "unboxing",
    scope: "video",
    label: "开箱视频",
    summary: "从包装到开箱，节奏轻快。",
    thumbnail: "/images/reference/sample-2.png",
    category: "商品美食",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 8,
    requiresImage: false,
    featured: true,
    prompt: "生成 TikTok 风格开箱展示短视频，从包装到取出商品，镜头节奏轻快，展示配件、质感和第一眼亮点。",
  },
  {
    id: "product-scene-video",
    scope: "video",
    label: "商品场景视频",
    summary: "放进真实环境，营造种草氛围。",
    thumbnail: "/auth-showcase/product-scene.png",
    category: "商品美食",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 8,
    requiresImage: false,
    featured: false,
    prompt: "生成商品场景展示短视频，商品出现在真实生活环境中，镜头有轻微推进和转场，氛围自然，适合 TikTok Shop 种草。",
  },
  {
    id: "promo-video",
    scope: "video",
    label: "促销广告短片",
    summary: "前几秒直接给卖点和氛围。",
    thumbnail: "/images/reference/sample-1.png",
    category: "海报品牌",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 10,
    requiresImage: false,
    featured: true,
    prompt: "生成促销短视频，前 2 秒快速展示商品和卖点，随后展示使用场景和优惠氛围，节奏明快，适合 TikTok Shop 推广。",
  },
  {
    id: "before-after",
    scope: "video",
    label: "前后对比",
    summary: "用前后变化突出效果。",
    thumbnail: "/images/reference/sample-2.png",
    category: "图片编辑",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 8,
    requiresImage: false,
    featured: false,
    prompt: "生成前后对比短视频，用清晰的前后变化展示商品效果，镜头简洁，节奏明快，适合转化表达。",
  },
  {
    id: "tiktok-ad",
    scope: "video",
    label: "TikTok 竖屏广告",
    summary: "竖屏节奏紧凑，适合投放。",
    thumbnail: "/images/reference/sample-3.png",
    category: "海报品牌",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 10,
    requiresImage: false,
    featured: false,
    prompt: "生成 TikTok 竖屏广告短视频，节奏紧凑，前几秒突出卖点，中段展示场景和细节，结尾带转化信息。",
  },
  {
    id: "cinematic-storyboard",
    scope: "video",
    label: "电影分镜",
    summary: "适合短片、预告和故事片段。",
    thumbnail: "/tutorials/video-generator/input-person.png",
    category: "摄影人像",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "16:9",
    duration: 8,
    requiresImage: false,
    featured: false,
    prompt: "生成横版电影感短片，一位人物在雨夜城市街头缓慢前行，镜头从中景推进到近景，霓虹倒影、湿润路面和自然表情，节奏克制，适合故事开场。",
  },
  {
    id: "travel-vlog",
    scope: "video",
    label: "旅行 Vlog",
    summary: "城市旅行、探店和生活记录。",
    thumbnail: "/tutorials/video-generator/rain-umbrella.png",
    category: "摄影人像",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 8,
    requiresImage: false,
    featured: false,
    prompt: "生成竖屏旅行 Vlog 片段，清晨城市街道、咖啡店门口、路牌、行人和阳光，镜头像手持手机自然移动，画面真实轻松，适合社交媒体开头。",
  },
  {
    id: "fashion-runway",
    scope: "video",
    label: "服装走秀",
    summary: "服装展示和品牌短片。",
    thumbnail: "/images/reference/sample-3.png",
    category: "商品美食",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 8,
    requiresImage: false,
    featured: false,
    prompt: "生成竖屏服装展示短片，模特在简洁空间中缓慢走动和转身，突出服装剪裁、面料和整体搭配，镜头稳定，品牌 lookbook 质感。",
  },
  {
    id: "animated-poster",
    scope: "video",
    label: "海报动效",
    summary: "让静态海报有轻微动态层次。",
    thumbnail: "/images/reference/sample-1.png",
    category: "海报品牌",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 5,
    requiresImage: false,
    featured: false,
    prompt: "生成竖屏海报动效短片，主体标题和背景图层轻微视差移动，光影缓慢变化，整体干净高级，不要剧烈闪烁，适合品牌活动预热视频。",
  },
];

export const featuredImagePromptTemplates = [
  imagePromptTemplates.find((template) => template.id === "product-hero"),
  imagePromptTemplates.find((template) => template.id === "premium-perfume"),
  imagePromptTemplates.find((template) => template.id === "typography-poster"),
  imagePromptTemplates.find((template) => template.id === "street-photography"),
  imagePromptTemplates.find((template) => template.id === "text-translation"),
].filter((template): template is ImagePromptTemplate => Boolean(template));

export const featuredVideoPromptTemplates = [
  videoPromptTemplates.find((template) => template.id === "product-rotation"),
  videoPromptTemplates.find((template) => template.id === "detail-closeup"),
  videoPromptTemplates.find((template) => template.id === "usage-demo"),
  videoPromptTemplates.find((template) => template.id === "cinematic-storyboard"),
  videoPromptTemplates.find((template) => template.id === "promo-video"),
].filter((template): template is VideoPromptTemplate => Boolean(template));

export function templateById(id: string) {
  return [...imagePromptTemplates, ...videoPromptTemplates].find((template) => template.id === id) || null;
}

export function templateCloneHref(id: string) {
  return `/?template=${encodeURIComponent(id)}`;
}

export function templateTabHref(scope: TemplatePromptTemplate["scope"]) {
  return `/templates?tab=${scope}`;
}

export function templateScopeLabel(scope: TemplatePromptTemplate["scope"]) {
  return scope === "image" ? "图片模板" : "视频模板";
}
