import type { WorkspaceImageMode, WorkspaceVideoMode } from "@/lib/workspace-registry";

export type TemplateCategory =
  | "商品美食"
  | "电商详情"
  | "海报品牌"
  | "社媒内容"
  | "摄影人像"
  | "插画风格"
  | "图文科普"
  | "界面设计"
  | "图片编辑";

type TemplateBase = {
  id: string;
  label: string;
  summary: string;
  thumbnail: string;
  category: TemplateCategory;
  prompt: string;
  requiresImage: boolean;
  featured: boolean;
};

export type ImagePromptTemplate = TemplateBase & {
  scope: "image";
  targetToolId: "image" | "image-editor";
  mode: WorkspaceImageMode;
  aspectRatio: string;
  quality: "1k" | "2k" | "4k";
};

export type VideoPromptTemplate = TemplateBase & {
  scope: "video";
  targetToolId: "video";
  mode: WorkspaceVideoMode;
  aspectRatio: string;
  duration: number;
};

export type TemplatePromptTemplate = ImagePromptTemplate | VideoPromptTemplate;

export const templateCategories: Array<TemplateCategory | "全部"> = [
  "全部",
  "商品美食",
  "电商详情",
  "海报品牌",
  "社媒内容",
  "摄影人像",
  "插画风格",
  "图文科普",
  "界面设计",
  "图片编辑",
];

export const imagePromptTemplates: ImagePromptTemplate[] = [
  {
    id: "product-hero",
    scope: "image",
    label: "商品主图",
    summary: "主体居中，背景干净，适合电商首图。",
    thumbnail: "/template-covers/product-hero.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: false,
    featured: true,
    prompt: "生成一张 TikTok Shop 商品主图，商品主体居中，占画面主要位置，背景干净，光线柔和，突出材质、颜色和核心卖点。",
  },
  {
    id: "white-background",
    scope: "image",
    label: "纯白背景",
    summary: "纯白背景，突出商品轮廓和质感。",
    thumbnail: "/template-covers/white-background.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: false,
    featured: true,
    prompt: "生成一张纯白背景商品图，主体边缘清晰，阴影自然，画面干净，适合 TikTok Shop 商品展示。",
  },
  {
    id: "product-scene",
    scope: "image",
    label: "商品场景图",
    summary: "把商品放进真实使用场景。",
    thumbnail: "/template-covers/product-scene.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: false,
    featured: true,
    prompt: "生成一张商品场景图，把商品放在真实使用环境中，场景自然、有生活感，突出商品用途和 TikTok Shop 转化卖点。",
  },
  {
    id: "premium-perfume",
    scope: "image",
    label: "新中式香水",
    summary: "东方空间、花材和产品质感结合。",
    thumbnail: "/template-covers/premium-perfume.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: true,
    prompt: "新中式香水产品摄影，粉色牡丹花簇拥，香水瓶置于大理石台面，背景带有中式窗棂元素，光影柔和，画面干净高级，细节丰富，商业产品图风格。",
  },
  {
    id: "food-editorial",
    scope: "image",
    label: "美食海报",
    summary: "适合餐饮新品、甜品和饮品展示。",
    thumbnail: "/template-covers/food-editorial.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "3:4",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "竖版 3:4 美食商业摄影，一份精致甜品放在陶瓷餐盘中，周围有新鲜水果、奶油和细小糖粉，暖色侧光，浅景深，背景干净，画面有菜单封面和社交媒体海报质感。",
  },
  {
    id: "fashion-editorial",
    scope: "image",
    label: "服装大片",
    summary: "服饰、配饰和生活方式视觉。",
    thumbnail: "/template-covers/fashion-editorial.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "2:3",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "竖版时尚编辑大片，一位模特穿着简洁高级的春夏服装，站在自然光室内空间，衣料纹理清楚，姿态自然，背景克制，整体像品牌 lookbook 封面，不出现真实品牌标识。",
  },
  {
    id: "promo-poster",
    scope: "image",
    label: "促销海报",
    summary: "预留促销信息位，突出活动氛围。",
    thumbnail: "/template-covers/promo-poster.png",
    category: "海报品牌",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "4:5",
    quality: "2k",
    requiresImage: false,
    featured: true,
    prompt: "设计一张 3:4 竖版促销海报，商品醒目，画面有活动氛围，预留清晰的标题、价格和行动按钮区域，层级明确，商业感强，适合社交媒体投放。",
  },
  {
    id: "typography-poster",
    scope: "image",
    label: "字体海报",
    summary: "强调标题文字和版式节奏。",
    thumbnail: "/template-covers/typography-poster.png",
    category: "海报品牌",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "3:4",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "设计一张 3:4 竖版字体海报，准确显示中文标题“夏日灵感周”和副标题“新鲜、明亮、轻盈”，大标题清楚可读，使用现代中文排版、网格系统、留白和少量粉紫强调色，不要出现乱码。",
  },
  {
    id: "brand-identity-board",
    scope: "image",
    label: "品牌视觉板",
    summary: "展示 Logo、色彩、包装和应用场景。",
    thumbnail: "/template-covers/brand-identity-board.png",
    category: "海报品牌",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 16:9 品牌视觉板，为一个虚构生活方式品牌“AURORA STUDIO”设计展示页，包含标志、主色板、字体样张、包装小样、社交媒体封面和名片应用，布局整洁，文字清晰，现代高级。",
  },
  {
    id: "event-poster",
    scope: "image",
    label: "活动主视觉",
    summary: "适合发布会、市集、展览活动。",
    thumbnail: "/template-covers/event-poster.png",
    category: "海报品牌",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 16:9 活动主视觉海报，主题是“城市创意生活节”，画面包含舞台、展位、灯光、人群剪影和品牌视觉元素，标题区清晰，留出日期和地点信息位置，风格年轻但不杂乱。",
  },
  {
    id: "portrait-studio",
    scope: "image",
    label: "棚拍人像",
    summary: "干净人像、头像和个人品牌照。",
    thumbnail: "/template-covers/portrait-studio.png",
    category: "摄影人像",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "2:3",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "竖版 2:3 专业棚拍人像，一位年轻创作者面对镜头，自然微笑，柔和主光和轮廓光，背景为深灰渐变，皮肤质感真实，服装简洁，适合个人主页头像和品牌介绍。",
  },
  {
    id: "street-photography",
    scope: "image",
    label: "街头摄影",
    summary: "真实城市氛围和自然光影。",
    thumbnail: "/template-covers/street-photography.png",
    category: "摄影人像",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 16:9 写实街头摄影，雨天中国城市街头，透明雨伞、湿润柏油路、霓虹招牌反光、行人和共享单车，画面像真实相机抓拍，光线自然，细节丰富，不过度电影化。",
  },
  {
    id: "interior-photography",
    scope: "image",
    label: "室内空间",
    summary: "家居、展厅和商业空间氛围图。",
    thumbnail: "/template-covers/interior-photography.png",
    category: "摄影人像",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 16:9 室内空间摄影，现代东方茶室，木质桌椅、低矮花器、亚麻窗帘、柔和天光和墙面投影，空间干净有层次，适合作为家居品牌或空间设计展示图。",
  },
  {
    id: "travel-photo",
    scope: "image",
    label: "旅行纪实",
    summary: "自然景观、城市旅行和生活方式。",
    thumbnail: "/template-covers/travel-photo.png",
    category: "摄影人像",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "3:2",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 3:2 旅行纪实照片，清晨古城街巷，石板路、木窗、早餐摊、远处行人和柔和阳光，色彩真实，像相机原片，有生活气息，不要过度滤镜。",
  },
  {
    id: "anime-character",
    scope: "image",
    label: "动漫角色",
    summary: "角色立绘、社交头像和设定稿。",
    thumbnail: "/template-covers/anime-character.png",
    category: "插画风格",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "2:3",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "竖版 2:3 动漫角色立绘，一位原创未来城市少女，短外套、耳机、发光配饰和轻便背包，站姿清楚，表情自信，背景简洁，线稿干净，配色统一，不模仿真实 IP。",
  },
  {
    id: "watercolor-illustration",
    scope: "image",
    label: "水彩插画",
    summary: "柔和手绘、书籍和包装插图。",
    thumbnail: "/template-covers/watercolor-illustration.png",
    category: "插画风格",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "4:3",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 4:3 水彩插画，一间安静花店，木质门头、玻璃窗、鲜花桶、猫和雨后街道，颜色柔和，纸张纹理可见，边缘自然晕染，适合绘本或生活方式品牌插图。",
  },
  {
    id: "chinese-ink",
    scope: "image",
    label: "国风水墨",
    summary: "东方审美、山水和留白构图。",
    thumbnail: "/template-covers/chinese-ink.png",
    category: "插画风格",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 16:9 现代国风水墨插画，远山、薄雾、松枝、小桥和一盏温暖灯光，墨色层次清楚，留白充足，少量淡粉色点缀，适合高端文化产品背景。",
  },
  {
    id: "pixel-game-scene",
    scope: "image",
    label: "像素场景",
    summary: "游戏封面、关卡氛围和复古视觉。",
    thumbnail: "/template-covers/pixel-game-scene.png",
    category: "插画风格",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 16:9 像素艺术游戏场景，夜晚小镇、雨水、便利店灯光、远处霓虹和主角背影，像素边缘清晰，色彩统一，有复古游戏封面感。",
  },
  {
    id: "tattoo-flash",
    scope: "image",
    label: "纹身图案",
    summary: "适合纹身闪图、图案设计和灵感板。",
    thumbnail: "/template-covers/tattoo-flash.png",
    category: "插画风格",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "2:3",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "竖版 2:3 纹身设计闪图，一只月亮飞蛾、黑玫瑰、细线星轨和轻微哥特装饰，黑灰线稿为主，少量冷紫色点缀，线条清晰，留白充足，像专业纹身图案展示纸，不出现真实皮肤。",
  },
  {
    id: "infographic-board",
    scope: "image",
    label: "信息图卡",
    summary: "拆解说明、知识卡片和流程图。",
    thumbnail: "/template-covers/infographic-board.png",
    category: "图文科普",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 16:9 中文信息图，主题“冷萃咖啡风味指南”，固定布局包含顶部标题、左侧风味轮、右侧制作流程、底部参数表，使用清晰中文标签、细线引导、柔和配色和充足留白，不要乱码。",
  },
  {
    id: "research-diagram",
    scope: "image",
    label: "论文示意图",
    summary: "研究流程、模型结构和论文插图。",
    thumbnail: "/template-covers/research-diagram.png",
    category: "图文科普",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 16:9 论文风格流程示意图，主题“多模态内容生成工作流”，从左到右包含输入、理解、规划、生成、质检五个模块，使用箭头、编号、图例和简洁标签，白底，学术会议图表质感。",
  },
  {
    id: "data-dashboard-card",
    scope: "image",
    label: "数据图表",
    summary: "报告、看板和趋势可视化。",
    thumbnail: "/template-covers/data-dashboard-card.png",
    category: "图文科普",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 16:9 数据可视化报告页，主题“内容投放效果概览”，包含折线图、柱状图、渠道占比、关键指标卡和简短中文注释，网格对齐，标签清晰，商务报告风格。",
  },
  {
    id: "field-guide",
    scope: "image",
    label: "科普图鉴",
    summary: "自然、器物和知识图鉴。",
    thumbnail: "/template-covers/field-guide.png",
    category: "图文科普",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "3:4",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "竖版 3:4 中文科普图鉴，主题“常见香料植物”，包含 6 个植物小图、名称标签、简短风味说明和底部说明栏，像博物馆展板，排版清楚，文字可读，不要乱码。",
  },
  {
    id: "wayfinding-map",
    scope: "image",
    label: "导览地图",
    summary: "景区、展馆和活动现场导览图。",
    thumbnail: "/template-covers/wayfinding-map.png",
    category: "图文科普",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "3:2",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "横版 3:2 中文导览地图，主题“城市创意市集导览图”，包含入口、主舞台、餐饮区、手作区、休息区、卫生间、服务台和出口，路线清楚，图例完整，插画风格友好，标签清晰可读。",
  },
  {
    id: "mobile-app-mockup",
    scope: "image",
    label: "手机界面",
    summary: "移动 App 首屏和产品概念稿。",
    thumbnail: "/template-covers/mobile-app-mockup.png",
    category: "界面设计",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "9:16",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "9:16 手机界面设计稿，为虚构习惯管理 App“Dayline”设计首页，包含顶部问候语、今日进度环、习惯列表、数据小卡片和底部导航，深色背景，粉紫强调色，图标对齐，文字清晰。",
  },
  {
    id: "saas-dashboard",
    scope: "image",
    label: "工作台界面",
    summary: "SaaS 后台、数据面板和工具页。",
    thumbnail: "/template-covers/saas-dashboard.png",
    category: "界面设计",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "16:9 桌面端 SaaS 工作台界面，为虚构 AI 内容平台设计深色仪表盘，包含左侧导航、顶部指标、任务列表、预览区和状态卡片，布局紧凑专业，组件边框细腻，文字清楚。",
  },
  {
    id: "landing-hero",
    scope: "image",
    label: "落地页首屏",
    summary: "产品官网、活动页和品牌首屏。",
    thumbnail: "/template-covers/landing-hero.png",
    category: "界面设计",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "16:9 产品落地页首屏视觉，为虚构创意工具“Aurora Canvas”设计网页首屏，左侧标题、短副标题和主要按钮，右侧为真实产品界面预览，深色高级风格，粉紫少量强调，排版清晰。",
  },
  {
    id: "app-icon-set",
    scope: "image",
    label: "图标套组",
    summary: "功能图标、应用图标和视觉系统。",
    thumbnail: "/template-covers/app-icon-set.png",
    category: "界面设计",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "正方形 1:1 图标套组，设计 12 个统一风格的 AI 创作工具图标，包含视频、图片、编辑、高清、模板、作品库等主题，线性加微渐变风格，圆角统一，深色背景上清晰可见。",
  },
  {
    id: "multi-angle",
    scope: "image",
    label: "多角度展示",
    summary: "用多角度展现商品外观。",
    thumbnail: "/template-covers/multi-angle.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成商品多角度展示图，围绕主体展示正面、侧面和细节视角，画面统一，适合 TikTok Shop 商品讲解。",
  },
  {
    id: "detail-shot",
    scope: "image",
    label: "商品细节图",
    summary: "放大材质、纹理和关键细节。",
    thumbnail: "/template-covers/detail-shot.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成商品细节展示图，突出材质、纹理、结构和功能亮点，画面干净，适合电商详情页。",
  },
  {
    id: "text-translation",
    scope: "image",
    label: "文字翻译",
    summary: "翻译画面文字，并保持原布局。",
    thumbnail: "/template-covers/text-translation.png",
    category: "图片编辑",
    targetToolId: "image-editor",
    mode: "image-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: true,
    featured: true,
    prompt: "基于上传图像翻译画面中的文字，保持原始排版、布局、字体风格和商品主体不变，翻译后画面自然清晰。",
  },
  {
    id: "smart-cutout",
    scope: "image",
    label: "智能抠图",
    summary: "自动抠出主体，保留边缘细节。",
    thumbnail: "/template-covers/smart-cutout.png",
    category: "图片编辑",
    targetToolId: "image-editor",
    mode: "image-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: true,
    featured: false,
    prompt: "基于上传图像智能抠出主体，保持原始比例和主体细节，输出透明背景，边缘干净自然。",
  },
  {
    id: "background-replace",
    scope: "image",
    label: "替换背景",
    summary: "保留主体，换成更适合的场景。",
    thumbnail: "/template-covers/background-replace.png",
    category: "图片编辑",
    targetToolId: "image-editor",
    mode: "image-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: true,
    featured: false,
    prompt: "基于上传图像保留主体、姿态和光影方向不变，将背景替换为干净高级的室内商业场景，主体边缘自然融合，材质和阴影保持真实。",
  },
  {
    id: "object-remove",
    scope: "image",
    label: "去除杂物",
    summary: "清理多余物体和画面干扰。",
    thumbnail: "/template-covers/object-remove.png",
    category: "图片编辑",
    targetToolId: "image-editor",
    mode: "image-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: true,
    featured: false,
    prompt: "基于上传图像去除画面中多余杂物、污渍、反光和背景干扰，保持主体、构图和真实光影不变，修复区域自然不可见。",
  },
  {
    id: "style-transfer",
    scope: "image",
    label: "风格统一",
    summary: "把素材统一成同一视觉风格。",
    thumbnail: "/template-covers/style-transfer.png",
    category: "图片编辑",
    targetToolId: "image-editor",
    mode: "image-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: true,
    featured: false,
    prompt: "基于上传图像保持主体结构和关键细节不变，将整体视觉统一为高级商业摄影风格，调整色彩、光影和背景质感，使画面更干净专业。",
  },
  {
    id: "detail-page-long",
    scope: "image",
    label: "详情页长图",
    summary: "卖点、参数、场景和对比一屏讲清。",
    thumbnail: "/template-covers/detail-page-long.png",
    category: "电商详情",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "9:16",
    quality: "2k",
    requiresImage: false,
    featured: true,
    prompt: "生成 9:16 电商详情页长图，顶部为商品主视觉，中部拆解 3 个核心卖点和材质细节，底部展示使用场景、尺寸参数和购买理由，中文信息层级清晰，留白充足，适合 TikTok Shop、独立站和商品详情页，不要出现乱码和虚假品牌。",
  },
  {
    id: "transparent-asset-pack",
    scope: "image",
    label: "透明素材包",
    summary: "抠出主体并整理成可复用商品素材。",
    thumbnail: "/template-covers/transparent-asset-pack.png",
    category: "图片编辑",
    targetToolId: "image-editor",
    mode: "image-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: true,
    featured: true,
    prompt: "基于上传图像抠出商品主体，输出透明背景商品素材，边缘干净自然，保留真实材质、颜色、反光和阴影关系，不改变商品结构，不添加新文字或新品牌，适合作为海报、详情页和短视频封面素材。",
  },
  {
    id: "feature-comparison",
    scope: "image",
    label: "卖点对比图",
    summary: "把产品优势和普通方案对比清楚。",
    thumbnail: "/template-covers/feature-comparison.png",
    category: "电商详情",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "4:5",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成 4:5 商品卖点对比图，左侧展示普通方案痛点，右侧展示本商品解决方案，中间用清晰箭头或分割线连接，包含 3 个短中文卖点标签，排版克制、信息易读、适合社媒广告和商品详情页，不要夸大医疗、功效或绝对化承诺。",
  },
  {
    id: "social-cover",
    scope: "image",
    label: "社媒封面",
    summary: "首屏抓眼的短视频或笔记封面。",
    thumbnail: "/template-covers/social-cover.png",
    category: "社媒内容",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "4:5",
    quality: "2k",
    requiresImage: false,
    featured: true,
    prompt: "生成 4:5 社媒内容封面，画面中心有明确主体，标题区清晰可读，预留 8 到 12 个中文字的位置，用强对比但不杂乱的构图吸引点击，适合小红书、TikTok、Instagram Reels 封面，不要出现无意义乱码。",
  },
  {
    id: "ugc-review-card",
    scope: "image",
    label: "UGC 种草卡",
    summary: "模拟真实用户推荐和使用体验。",
    thumbnail: "/template-covers/ugc-review-card.png",
    category: "社媒内容",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "3:4",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成 3:4 UGC 种草卡片，画面像真实用户分享，包含自然使用场景、商品局部、轻量评价标签和生活化背景，整体真实可信，不像硬广，适合短视频封面和图文笔记，不要出现真实平台水印和虚假用户头像。",
  },
  {
    id: "bundle-set",
    scope: "image",
    label: "套装组合图",
    summary: "把多件商品整理成套装展示。",
    thumbnail: "/template-covers/bundle-set.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成 1:1 商品套装组合图，主商品居中，配件或赠品围绕摆放，层次清楚，背景干净，突出组合价值和购买理由，适合电商首图与套装页。",
  },
  {
    id: "beauty-texture",
    scope: "image",
    label: "美妆质地图",
    summary: "展示膏体、液体、粉质和肤感。",
    thumbnail: "/template-covers/beauty-texture.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "4:5",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成 4:5 美妆产品质地图，包含产品瓶身、质地涂抹、细腻高光和柔和背景，突出清透、滋润或哑光等触感，不出现夸大功效文案。",
  },
  {
    id: "jewelry-luxury",
    scope: "image",
    label: "珠宝奢华图",
    summary: "金属、宝石和高级礼盒氛围。",
    thumbnail: "/template-covers/jewelry-luxury.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "1:1",
    quality: "4k",
    requiresImage: false,
    featured: false,
    prompt: "生成珠宝或配饰高级商品图，金属与宝石细节清晰，背景为深色丝绒或礼盒场景，光线有精致反射，构图简洁，不添加虚假品牌。",
  },
  {
    id: "home-lifestyle",
    scope: "image",
    label: "家居生活图",
    summary: "家具、家电和生活方式场景。",
    thumbnail: "/template-covers/home-lifestyle.png",
    category: "商品美食",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成家居生活方式商品图，把家具、家电或日用品放在真实居家空间中，自然光、整洁陈列、生活感强，突出尺寸、质感和使用场景。",
  },
  {
    id: "menu-board",
    scope: "image",
    label: "菜单价目表",
    summary: "餐饮菜单、价格和新品推荐。",
    thumbnail: "/template-covers/menu-board.png",
    category: "图文科普",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "4:5",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成餐饮菜单价目表海报，包含 4 到 6 个菜品或饮品区域、价格位置、新品推荐标签和清晰中文排版，画面干净有食欲，不要乱码。",
  },
  {
    id: "course-cover",
    scope: "image",
    label: "课程封面",
    summary: "知识付费、直播课和训练营封面。",
    thumbnail: "/template-covers/course-cover.png",
    category: "社媒内容",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成 16:9 课程封面，中心突出课程主题和讲师形象或知识符号，标题区清晰，副标题和时间信息层级明确，适合直播课、训练营和知识分享。",
  },
  {
    id: "podcast-cover",
    scope: "image",
    label: "播客封面",
    summary: "播客、电台、音乐和访谈视觉。",
    thumbnail: "/template-covers/podcast-cover.png",
    category: "社媒内容",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成 1:1 播客封面，包含节目名称预留区、主持人或抽象主题视觉、清晰对比和平台缩略图可读性，风格专业但有记忆点。",
  },
  {
    id: "recruitment-poster",
    scope: "image",
    label: "招聘海报",
    summary: "岗位招聘、门店招人和团队招募。",
    thumbnail: "/template-covers/recruitment-poster.png",
    category: "海报品牌",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "4:5",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成招聘海报，包含岗位标题、3 个岗位亮点、薪资福利信息区、联系方式位置和积极团队氛围，中文排版清晰，适合朋友圈和门店张贴。",
  },
  {
    id: "real-estate-card",
    scope: "image",
    label: "房产展示卡",
    summary: "户型、卖点和小区环境展示。",
    thumbnail: "/template-covers/real-estate-card.png",
    category: "海报品牌",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "4:5",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成房产展示卡片，突出室内空间、户型亮点、面积和位置优势，排版稳重可信，图片区域大，文字信息克制清楚，不做虚假承诺。",
  },
  {
    id: "holiday-campaign",
    scope: "image",
    label: "节日活动图",
    summary: "节日促销、祝福和活动主视觉。",
    thumbnail: "/template-covers/holiday-campaign.png",
    category: "海报品牌",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "9:16",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成竖屏节日活动主视觉，包含节日氛围、活动标题、优惠信息区和商品或品牌露出，画面热闹但不杂乱，适合春节、中秋、双十一或周年庆。",
  },
  {
    id: "comic-strip",
    scope: "image",
    label: "四格漫画",
    summary: "用小故事解释产品或观点。",
    thumbnail: "/template-covers/comic-strip.png",
    category: "插画风格",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "4:5",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成四格漫画，按起因、冲突、解决、结果四个画面讲清一个产品使用或生活小故事，角色表情明确，分镜清楚，文字少且可读。",
  },
  {
    id: "children-book",
    scope: "image",
    label: "绘本插画",
    summary: "儿童绘本、故事书和温柔插图。",
    thumbnail: "/template-covers/children-book.png",
    category: "插画风格",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "4:5",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成儿童绘本风插画，角色友好，色彩柔和，场景有故事感，构图清晰，适合绘本页面、亲子活动和教育内容，不出现恐怖或成人化元素。",
  },
  {
    id: "avatar-pack",
    scope: "image",
    label: "头像套组",
    summary: "社交头像、IP 形象和角色表情。",
    thumbnail: "/template-covers/avatar-pack.png",
    category: "插画风格",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成 1:1 头像套组视觉，角色正面清晰，表情亲和，背景简洁，适合社交头像、品牌 IP 或客服头像，风格统一且易识别。",
  },
  {
    id: "step-tutorial",
    scope: "image",
    label: "步骤教程图",
    summary: "操作步骤、使用说明和流程拆解。",
    thumbnail: "/template-covers/step-tutorial.png",
    category: "图文科普",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "4:5",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成步骤教程图，按 1、2、3、4 展示操作流程，每步有图标、短标题和说明区域，信息清楚，适合产品说明、教程笔记和售后指南。",
  },
  {
    id: "medical-wellness-card",
    scope: "image",
    label: "健康科普卡",
    summary: "健康知识、护理提示和注意事项。",
    thumbnail: "/template-covers/medical-wellness-card.png",
    category: "图文科普",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "4:5",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成健康科普卡片，包含一个明确主题、3 到 5 条注意事项和温和可信的插图，排版专业克制，不给诊断结论，不夸大疗效。",
  },
  {
    id: "app-store-screens",
    scope: "image",
    label: "应用商店图",
    summary: "App 功能截图和卖点展示。",
    thumbnail: "/template-covers/app-store-screens.png",
    category: "界面设计",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "9:16",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成应用商店竖屏展示图，包含手机界面、功能卖点标题和简洁背景，突出 3 个核心功能，像真实 App Store 或应用市场素材，不要使用真实平台商标。",
  },
  {
    id: "website-section",
    scope: "image",
    label: "网页模块",
    summary: "官网区块、产品模块和服务介绍。",
    thumbnail: "/template-covers/website-section.png",
    category: "界面设计",
    targetToolId: "image",
    mode: "text-to-image",
    aspectRatio: "16:9",
    quality: "2k",
    requiresImage: false,
    featured: false,
    prompt: "生成官网网页模块视觉，包含清晰标题、产品或服务展示区、功能卖点和按钮位置，布局现代、留白充足，适合 SaaS、品牌官网或服务页。",
  },
  {
    id: "remove-watermark-layout",
    scope: "image",
    label: "清理水印杂字",
    summary: "清理水印、杂字和多余遮挡。",
    thumbnail: "/template-covers/remove-watermark-layout.png",
    category: "图片编辑",
    targetToolId: "image-editor",
    mode: "image-to-image",
    aspectRatio: "1:1",
    quality: "2k",
    requiresImage: true,
    featured: false,
    prompt: "基于上传图像清理水印、杂字、贴纸或多余遮挡，保留主体、背景纹理、光影和透视一致，修补区域自然，不改变商品结构和画面含义。",
  },
  {
    id: "old-photo-restore",
    scope: "image",
    label: "老照片修复",
    summary: "修复划痕、褪色和模糊照片。",
    thumbnail: "/template-covers/old-photo-restore.png",
    category: "图片编辑",
    targetToolId: "image-editor",
    mode: "image-to-image",
    aspectRatio: "3:4",
    quality: "2k",
    requiresImage: true,
    featured: false,
    prompt: "基于上传老照片进行修复，去除划痕、污点和轻微模糊，恢复自然肤色和细节，保留人物身份、服装、年代感和原始构图，不要过度美颜。",
  },
  {
    id: "virtual-try-on",
    scope: "image",
    label: "虚拟试穿",
    summary: "服装上身、搭配和尺码感展示。",
    thumbnail: "/template-covers/virtual-try-on.png",
    category: "图片编辑",
    targetToolId: "image-editor",
    mode: "image-to-image",
    aspectRatio: "3:4",
    quality: "2k",
    requiresImage: true,
    featured: false,
    prompt: "基于上传服装或人物图进行虚拟试穿，保持人物姿态和身份自然，展示服装版型、材质和搭配效果，边缘贴合真实，不改变人物体型特征。",
  },
];

export const videoPromptTemplates: VideoPromptTemplate[] = [
  {
    id: "product-rotation",
    scope: "video",
    label: "商品旋转",
    summary: "商品缓慢旋转，突出外观和质感。",
    thumbnail: "/template-covers/product-rotation.png",
    category: "商品美食",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 5,
    requiresImage: false,
    featured: true,
    prompt: "生成 TikTok Shop 商品旋转展示短视频，商品居中缓慢旋转，镜头稳定，光线干净，突出外观、材质和卖点。",
  },
  {
    id: "detail-closeup",
    scope: "video",
    label: "细节特写",
    summary: "镜头推进，展示商品细节。",
    thumbnail: "/template-covers/detail-closeup.png",
    category: "商品美食",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 5,
    requiresImage: false,
    featured: true,
    prompt: "生成商品细节特写短视频，镜头缓慢推进，展示材质、纹理、按键、接口或功能细节，节奏清楚，适合 TikTok 商品展示。",
  },
  {
    id: "usage-demo",
    scope: "video",
    label: "使用展示",
    summary: "展示真实使用动作和效果。",
    thumbnail: "/template-covers/usage-demo.png",
    category: "商品美食",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 8,
    requiresImage: false,
    featured: true,
    prompt: "生成穿戴或使用展示短视频，展示用户如何自然使用商品，动作连贯，场景真实，突出使用效果和日常适用性。",
  },
  {
    id: "unboxing",
    scope: "video",
    label: "开箱视频",
    summary: "从包装到开箱，节奏轻快。",
    thumbnail: "/template-covers/unboxing.png",
    category: "商品美食",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 8,
    requiresImage: false,
    featured: true,
    prompt: "生成 TikTok 风格开箱展示短视频，从包装到取出商品，镜头节奏轻快，展示配件、质感和第一眼亮点。",
  },
  {
    id: "product-scene-video",
    scope: "video",
    label: "商品场景视频",
    summary: "放进真实环境，营造种草氛围。",
    thumbnail: "/template-covers/product-scene-video.png",
    category: "商品美食",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 8,
    requiresImage: false,
    featured: false,
    prompt: "生成商品场景展示短视频，商品出现在真实生活环境中，镜头有轻微推进和转场，氛围自然，适合 TikTok Shop 种草。",
  },
  {
    id: "promo-video",
    scope: "video",
    label: "促销广告短片",
    summary: "前几秒直接给卖点和氛围。",
    thumbnail: "/template-covers/promo-video.png",
    category: "海报品牌",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 10,
    requiresImage: false,
    featured: true,
    prompt: "生成促销短视频，前 2 秒快速展示商品和卖点，随后展示使用场景和优惠氛围，节奏明快，适合 TikTok Shop 推广。",
  },
  {
    id: "before-after",
    scope: "video",
    label: "前后对比",
    summary: "用前后变化突出效果。",
    thumbnail: "/template-covers/before-after.png",
    category: "图片编辑",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 8,
    requiresImage: false,
    featured: false,
    prompt: "生成前后对比短视频，用清晰的前后变化展示商品效果，镜头简洁，节奏明快，适合转化表达。",
  },
  {
    id: "tiktok-ad",
    scope: "video",
    label: "TikTok 竖屏广告",
    summary: "竖屏节奏紧凑，适合投放。",
    thumbnail: "/template-covers/tiktok-ad.png",
    category: "海报品牌",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 10,
    requiresImage: false,
    featured: false,
    prompt: "生成 TikTok 竖屏广告短视频，节奏紧凑，前几秒突出卖点，中段展示场景和细节，结尾带转化信息。",
  },
  {
    id: "cinematic-storyboard",
    scope: "video",
    label: "电影分镜",
    summary: "适合短片、预告和故事片段。",
    thumbnail: "/template-covers/cinematic-storyboard.png",
    category: "摄影人像",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "16:9",
    duration: 8,
    requiresImage: false,
    featured: false,
    prompt: "生成横版电影感短片，一位人物在雨夜城市街头缓慢前行，镜头从中景推进到近景，霓虹倒影、湿润路面和自然表情，节奏克制，适合故事开场。",
  },
  {
    id: "travel-vlog",
    scope: "video",
    label: "旅行 Vlog",
    summary: "城市旅行、探店和生活记录。",
    thumbnail: "/template-covers/travel-vlog.png",
    category: "摄影人像",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 8,
    requiresImage: false,
    featured: false,
    prompt: "生成竖屏旅行 Vlog 片段，清晨城市街道、咖啡店门口、路牌、行人和阳光，镜头像手持手机自然移动，画面真实轻松，适合社交媒体开头。",
  },
  {
    id: "fashion-runway",
    scope: "video",
    label: "服装走秀",
    summary: "服装展示和品牌短片。",
    thumbnail: "/template-covers/fashion-runway.png",
    category: "商品美食",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 8,
    requiresImage: false,
    featured: false,
    prompt: "生成竖屏服装展示短片，模特在简洁空间中缓慢走动和转身，突出服装剪裁、面料和整体搭配，镜头稳定，品牌 lookbook 质感。",
  },
  {
    id: "animated-poster",
    scope: "video",
    label: "海报动效",
    summary: "让静态海报有轻微动态层次。",
    thumbnail: "/template-covers/animated-poster.png",
    category: "海报品牌",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 5,
    requiresImage: false,
    featured: false,
    prompt: "生成竖屏海报动效短片，主体标题和背景图层轻微视差移动，光影缓慢变化，整体干净高级，不要剧烈闪烁，适合品牌活动预热视频。",
  },
  {
    id: "ugc-hook-video",
    scope: "video",
    label: "UGC 开头钩子",
    summary: "前 3 秒抓住注意力，像真实推荐。",
    thumbnail: "/template-covers/ugc-hook-video.png",
    category: "社媒内容",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 8,
    requiresImage: false,
    featured: true,
    prompt: "生成 9:16 UGC 种草短视频，前 3 秒用真实生活场景快速展示痛点和商品，随后切到使用动作和效果细节，镜头像手机拍摄，自然手持、轻微运动、真实可信，不要过度广告感，适合 TikTok 和 Reels。",
  },
  {
    id: "problem-solution-video",
    scope: "video",
    label: "问题解决短片",
    summary: "痛点、使用、结果三段式表达。",
    thumbnail: "/template-covers/problem-solution-video.png",
    category: "电商详情",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 10,
    requiresImage: false,
    featured: false,
    prompt: "生成 9:16 问题解决型商品短片，第一段展示用户痛点，第二段展示商品被自然使用，第三段展示改善后的结果和核心卖点，镜头顺序清晰，动作连贯，节奏适合 10 秒短视频，不添加夸张功效承诺。",
  },
  {
    id: "talking-head-script",
    scope: "video",
    label: "口播讲解",
    summary: "人物口播、产品讲解和带货开场。",
    thumbnail: "/template-covers/talking-head-script.png",
    category: "社媒内容",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 8,
    requiresImage: false,
    featured: false,
    prompt: "生成竖屏口播讲解短片，一位真实自然的创作者面对镜头介绍商品或观点，表情自然，手势克制，背景干净有生活感，镜头稳定，适合带货开场、知识分享或产品亮点说明，不要出现夸张表演。",
  },
  {
    id: "three-shot-storyboard",
    scope: "video",
    label: "三镜头分镜",
    summary: "建立场景、展示细节、给出结果。",
    thumbnail: "/template-covers/three-shot-storyboard.png",
    category: "海报品牌",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "16:9",
    duration: 8,
    requiresImage: false,
    featured: false,
    prompt: "生成横版三镜头分镜短片，镜头一建立场景和情绪，镜头二推近主体展示关键细节，镜头三给出完整结果或品牌氛围，转场自然，光线统一，适合品牌短片、活动预告和产品故事片段。",
  },
  {
    id: "customer-testimonial",
    scope: "video",
    label: "用户证言",
    summary: "真实用户反馈和体验分享。",
    thumbnail: "/template-covers/customer-testimonial.png",
    category: "社媒内容",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 8,
    requiresImage: false,
    featured: false,
    prompt: "生成竖屏用户证言短视频，一位真实用户在生活场景中自然分享使用体验，镜头稳定，表情可信，商品适度露出，避免夸张承诺和硬广口吻。",
  },
  {
    id: "countdown-sale",
    scope: "video",
    label: "倒计时促销",
    summary: "限时活动、秒杀和上新预热。",
    thumbnail: "/template-covers/countdown-sale.png",
    category: "海报品牌",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 5,
    requiresImage: false,
    featured: false,
    prompt: "生成竖屏倒计时促销短片，画面包含商品、倒计时节奏、优惠氛围和结尾停留画面，动效清晰不闪烁，适合限时上新和直播预热。",
  },
  {
    id: "food-prep",
    scope: "video",
    label: "美食制作",
    summary: "食材、烹饪过程和成品展示。",
    thumbnail: "/template-covers/food-prep.png",
    category: "商品美食",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 10,
    requiresImage: false,
    featured: false,
    prompt: "生成竖屏美食制作短视频，从食材准备、关键烹饪动作到成品特写，镜头节奏有食欲，蒸汽、酱汁和质感真实，适合餐饮新品或食谱内容。",
  },
  {
    id: "room-tour",
    scope: "video",
    label: "空间导览",
    summary: "家居、门店、展厅和民宿展示。",
    thumbnail: "/template-covers/room-tour.png",
    category: "摄影人像",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "16:9",
    duration: 8,
    requiresImage: false,
    featured: false,
    prompt: "生成空间导览短视频，镜头从入口缓慢推进，展示整体布局、细节陈列和光线氛围，运动平稳，适合家居、门店、展厅、民宿或房产展示。",
  },
  {
    id: "app-demo-video",
    scope: "video",
    label: "App 演示",
    summary: "应用功能、界面流程和产品介绍。",
    thumbnail: "/template-covers/app-demo-video.png",
    category: "界面设计",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 8,
    requiresImage: false,
    featured: false,
    prompt: "生成竖屏 App 功能演示短片，手机界面清楚，按打开、点击、功能结果的顺序展示，背景简洁，适合应用介绍、SaaS 功能和产品教程。",
  },
  {
    id: "logo-reveal",
    scope: "video",
    label: "Logo 片头",
    summary: "品牌开场、片头和结尾露出。",
    thumbnail: "/template-covers/logo-reveal.png",
    category: "海报品牌",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "16:9",
    duration: 5,
    requiresImage: false,
    featured: false,
    prompt: "生成横版 Logo 片头动效，品牌标识从干净背景中自然出现，光影高级，节奏克制，结尾停留 1 秒，适合视频开头、品牌短片和课程片头。",
  },
  {
    id: "tutorial-video",
    scope: "video",
    label: "教程步骤",
    summary: "产品教程、软件教学和操作说明。",
    thumbnail: "/template-covers/tutorial-video.png",
    category: "图文科普",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 10,
    requiresImage: false,
    featured: false,
    prompt: "生成竖屏教程步骤短视频，按 1、2、3 展示操作流程，每步画面清楚，手势或界面动作明确，节奏适合教学，不要出现看不清的密集文字。",
  },
  {
    id: "fitness-demo",
    scope: "video",
    label: "健身动作",
    summary: "运动教程、器材展示和训练片段。",
    thumbnail: "/template-covers/fitness-demo.png",
    category: "摄影人像",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 8,
    requiresImage: false,
    featured: false,
    prompt: "生成竖屏健身动作展示短片，人物动作标准、节奏稳定，展示器材或训练姿势，背景干净，适合运动课程、器材展示和健康内容。",
  },
  {
    id: "beauty-routine",
    scope: "video",
    label: "美妆流程",
    summary: "护肤、上妆和产品使用过程。",
    thumbnail: "/template-covers/beauty-routine.png",
    category: "商品美食",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 10,
    requiresImage: false,
    featured: false,
    prompt: "生成竖屏美妆护肤流程短视频，从取用产品、涂抹质地到自然完成效果，镜头干净柔和，突出真实肤感和产品质地，不夸大功效。",
  },
  {
    id: "game-trailer",
    scope: "video",
    label: "游戏预告",
    summary: "游戏场景、角色和玩法氛围。",
    thumbnail: "/template-covers/game-trailer.png",
    category: "插画风格",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "16:9",
    duration: 8,
    requiresImage: false,
    featured: false,
    prompt: "生成横版游戏预告短片，展示角色、场景、动作和玩法氛围，镜头有节奏变化，画面清晰，适合像素、二次元或独立游戏宣传。",
  },
  {
    id: "real-estate-tour",
    scope: "video",
    label: "房产看房",
    summary: "户型、采光和空间动线展示。",
    thumbnail: "/template-covers/real-estate-tour.png",
    category: "电商详情",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "16:9",
    duration: 10,
    requiresImage: false,
    featured: false,
    prompt: "生成房产看房短视频，镜头从客厅到卧室再到窗景，展示采光、空间动线和装修细节，画面真实可信，适合房产中介和民宿展示。",
  },
  {
    id: "product-comparison-video",
    scope: "video",
    label: "产品对比",
    summary: "两种方案、前后效果和卖点比较。",
    thumbnail: "/template-covers/product-comparison-video.png",
    category: "电商详情",
    targetToolId: "video",
    mode: "text-to-video",
    aspectRatio: "9:16",
    duration: 8,
    requiresImage: false,
    featured: false,
    prompt: "生成竖屏产品对比短视频，左侧或前半段展示普通方案，右侧或后半段展示本产品优势，镜头节奏清楚，结果可信，不使用夸张绝对化承诺。",
  },
];

const templateRailLimit = 8;

function templateRailTemplates<T extends TemplatePromptTemplate>(templates: T[]) {
  return templates
    .map((template, index) => ({ template, index }))
    .sort((left, right) => {
      const featuredDelta = Number(right.template.featured) - Number(left.template.featured);
      return featuredDelta || left.index - right.index;
    })
    .slice(0, templateRailLimit)
    .map(({ template }) => template);
}

export const featuredImagePromptTemplates = templateRailTemplates(imagePromptTemplates);

export const featuredImageGenerationPromptTemplates = templateRailTemplates(
  imagePromptTemplates.filter((template) => template.targetToolId === "image"),
);

export const featuredVideoPromptTemplates = templateRailTemplates(videoPromptTemplates);

export function templateById(id: string) {
  return [...imagePromptTemplates, ...videoPromptTemplates].find((template) => template.id === id) || null;
}

export function templateCloneHref(id: string) {
  return `/?template=${encodeURIComponent(id)}`;
}

export function templateTabHref(scope: TemplatePromptTemplate["scope"]) {
  return `/templates?tab=${scope}`;
}

export function templateScopeLabel(scope: TemplatePromptTemplate["scope"]) {
  return scope === "image" ? "图片模板" : "视频模板";
}
